"use client"

import { useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { api } from '@/lib/api';

const BlogCard = ({ blog }) => {
  const [liked, setLiked] = useState(blog.liked || false);
  const [likesCount, setLikesCount] = useState(blog.likesCount || 0);

  const handleLike = async () => {
    try {
      const response = await api.likeBlog(blog.id);
      setLiked(response.liked);
      setLikesCount(response.likesCount);
    } catch (error) {
      console.error('Error liking blog:', error);
    }
  };

  return (
    <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl overflow-hidden border border-gray-700 hover:border-blue-500 transition duration-300 hover:shadow-2xl hover:shadow-blue-900/20 group">
      {/* Book Cover */}
      {blog.bookDetails?.thumbnail && (
        <div className="relative h-48 overflow-hidden">
          <Image
            src={blog.bookDetails.thumbnail}
            alt={blog.bookDetails.title}
            fill
            className="object-cover group-hover:scale-105 transition duration-500"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-gray-900 via-transparent to-transparent" />
        </div>
      )}

      {/* Content */}
      <div className="p-6">
        {/* Category */}
        {blog.category && (
          <span className="inline-block px-3 py-1 text-xs bg-gradient-to-r from-blue-900/50 to-purple-900/50 rounded-full mb-3">
            {blog.category}
          </span>
        )}

        {/* Title */}
        <Link href={`/blogs/${blog.slug}`}>
          <h3 className="text-xl font-bold mb-3 hover:text-blue-400 transition duration-200 line-clamp-2">
            {blog.title}
          </h3>
        </Link>

        {/* Excerpt */}
        <p className="text-gray-300 mb-4 line-clamp-3">
          {blog.excerpt || blog.aiResponseExcerpt}
        </p>

        {/* Meta Info */}
        <div className="flex items-center justify-between text-sm text-gray-400">
          <div className="flex items-center gap-4">
            <button
              onClick={handleLike}
              className={`flex items-center gap-1 ${
                liked ? 'text-red-500' : 'hover:text-red-400'
              } transition duration-200`}
            >
              ♥ {likesCount}
            </button>
            <span className="flex items-center gap-1">
              👁️ {blog.views || 0}
            </span>
            <span className="flex items-center gap-1">
              💬 {blog.commentsCount || 0}
            </span>
          </div>
          <span>{new Date(blog.createdAt).toLocaleDateString()}</span>
        </div>

        {/* Author */}
        <div className="mt-4 pt-4 border-t border-gray-700 flex items-center gap-3">
          <div className="w-8 h-8 rounded-full bg-gradient-to-r from-blue-600 to-purple-600 flex items-center justify-center">
            <span className="text-xs font-bold">
              {blog.user?.username?.charAt(0) || 'A'}
            </span>
          </div>
          <div>
            <p className="text-sm font-medium">
              {blog.user?.username || 'Anonymous'}
            </p>
            <p className="text-xs text-gray-400">
              {blog.isAutoGenerated ? 'AI Generated' : 'Community Post'}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BlogCard;